export const data = [
  {
    ID: 'Byleth (M)',
    Faction: 'Church of Seiros',
    Gender: 'M',
    RecruitReq: 'From start',
    BaseHp: '27',
    BaseStr: '13',
    BaseMag: '6',
    BaseDex: '9',
    BaseSpd: '8',
    BaseLuck: '8',
    BaseDef: '6',
    BaseRes: '6',
    BaseCha: '7',
    GrowthHP: '45',
    GrowthStr: '45',
    GrowthMag: '35',
    GrowthDex: '45',
    GrowthSpd: '45',
    GrowthLck: '45',
    GrowthDef: '35',
    GrowthRes: '30',
    GrowthCha: '45',
    MaxHp: '88',
    MaxStr: '77',
    MaxMag: '55',
    MaxDex: '66',
    MaxSpd: '66',
    MaxLuck: '66',
    MaxDef: '55',
    MaxRes: '55',
    MaxCha: '99',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: 'U',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: 'U',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: 'D+',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: 'E+',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'D',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': 'Flames',
    'Minor Crest': '-',
    Supports:
      'Edelgard, Hubert, Dorothea, Ferdinand, Bernadetta, Caspar, Petra, Linhardt, Dimitri, Dedue, Felix, Mercedes, Ashe, Annette, Sylvain, Ingrid, Claude, Lorenz, Hilda, Raphael, Lysithea, Ignatz, Marianne, Leonie, Rhea, Manuela, Hanneman, Seteth, Flayn, Cyril, Jeralt, Catherine, Alois, Gilbert, Shamir, Rhea, Sothis',
  },
  {
    ID: 'Byleth (F)',
    Faction: 'Church of Seiros',
    Gender: 'F',
    RecruitReq: 'From start',
    BaseHp: '27',
    BaseStr: '13',
    BaseMag: '6',
    BaseDex: '9',
    BaseSpd: '8',
    BaseLuck: '8',
    BaseDef: '6',
    BaseRes: '6',
    BaseCha: '7',
    GrowthHP: '45',
    GrowthStr: '45',
    GrowthMag: '35',
    GrowthDex: '45',
    GrowthSpd: '45',
    GrowthLck: '45',
    GrowthDef: '35',
    GrowthRes: '30',
    GrowthCha: '45',
    MaxHp: '88',
    MaxStr: '77',
    MaxMag: '55',
    MaxDex: '66',
    MaxSpd: '66',
    MaxLuck: '66',
    MaxDef: '55',
    MaxRes: '55',
    MaxCha: '99',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: 'U',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: 'U',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: 'D+',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: 'E+',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'D',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': 'Flames',
    'Minor Crest': '-',
    Supports:
      'Edelgard, Hubert, Dorothea, Ferdinand, Bernadetta, Caspar, Petra, Linhardt, Dimitri, Dedue, Felix, Mercedes, Ashe, Annette, Sylvain, Ingrid, Claude, Lorenz, Hilda, Raphael, Lysithea, Ignatz, Marianne, Leonie, Rhea, Manuela, Hanneman, Seteth, Flayn, Cyril, Jeralt, Catherine, Alois, Gilbert, Shamir, Rhea, Sothis',
  },
  {
    ID: 'Edelgard',
    Faction: 'Black Eagles',
    Gender: 'F',
    RecruitReq: 'Black Eagle only',
    BaseHp: '29',
    BaseStr: '13',
    BaseMag: '6',
    BaseDex: '5',
    BaseSpd: '8',
    BaseLuck: '5',
    BaseDef: '6',
    BaseRes: '4',
    BaseCha: '10',
    GrowthHP: '40',
    GrowthStr: '55',
    GrowthMag: '45',
    GrowthDex: '45',
    GrowthSpd: '40',
    GrowthLck: '30',
    GrowthDef: '35',
    GrowthRes: '35',
    GrowthCha: '60',
    MaxHp: '81',
    MaxStr: '81',
    MaxMag: '72',
    MaxDex: '61',
    MaxSpd: '57',
    MaxLuck: '42',
    MaxDef: '61',
    MaxRes: '47',
    MaxCha: '85',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: 'U',
    BowProficiency: 'D',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: 'D',
    AuthorityProficiency: 'U',
    ArmorProficiency: 'U',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: 'E+',
    BaseLance: '-',
    BaseAxe: 'D',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'D',
    BaseArmor: 'D',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': 'Flames',
    'Minor Crest': 'Seiros',
    Supports:
      'BylethM, BylethF, Hubert, Ferdinand, Linhardt, Caspar, Bernadetta, Dorothea, Petra, Lysithea, Hanneman, Manuela',
  },
  {
    ID: 'Hubert',
    Faction: 'Black Eagles',
    Gender: 'M',
    RecruitReq: 'Black Eagle only',
    BaseHp: '22',
    BaseStr: '6',
    BaseMag: '12',
    BaseDex: '6',
    BaseSpd: '7',
    BaseLuck: '6',
    BaseDef: '4',
    BaseRes: '7',
    BaseCha: '6',
    GrowthHP: '35',
    GrowthStr: '30',
    GrowthMag: '55',
    GrowthDex: '45',
    GrowthSpd: '45',
    GrowthLck: '35',
    GrowthDef: '25',
    GrowthRes: '40',
    GrowthCha: '35',
    MaxHp: '67',
    MaxStr: '43',
    MaxMag: '80',
    MaxDex: '62',
    MaxSpd: '63',
    MaxLuck: '51',
    MaxDef: '45',
    MaxRes: '57',
    MaxCha: '49',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: 'D',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: 'U',
    FaithProficiency: 'D',
    AuthorityProficiency: 'U',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: 'D',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: 'E+',
    BaseBrawling: '-',
    BaseReason: 'D',
    BaseFaith: '-',
    BaseAuthority: 'E+',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Edelgard, Ferdinand, Linhardt, Caspar, Bernadetta, Dorothea, Petra, Hanneman, Shamir',
  },
  {
    ID: 'Dorothea',
    Faction: 'Black Eagles',
    Gender: 'F',
    RecruitReq: 'Need 25 Charm and B in Authority',
    BaseHp: '24',
    BaseStr: '5',
    BaseMag: '11',
    BaseDex: '6',
    BaseSpd: '7',
    BaseLuck: '6',
    BaseDef: '4',
    BaseRes: '7',
    BaseCha: '8',
    GrowthHP: '40',
    GrowthStr: '20',
    GrowthMag: '40',
    GrowthDex: '45',
    GrowthSpd: '40',
    GrowthLck: '35',
    GrowthDef: '15',
    GrowthRes: '35',
    GrowthCha: '40',
    MaxHp: '76',
    MaxStr: '30',
    MaxMag: '61',
    MaxDex: '62',
    MaxSpd: '57',
    MaxLuck: '49',
    MaxDef: '38',
    MaxRes: '50',
    MaxCha: '58',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: 'U',
    FaithProficiency: 'D',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: 'D',
    FlyingProficiency: 'D',
    BaseSword: 'E+',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: 'D',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Edelgard, Hubert, Ferdinand, Linhardt, Caspar, Bernadetta, Felix, Sylvain, Ingrid, Petra, Lorenz, Hanneman, Manuela',
  },
  {
    ID: 'Ferdinand',
    Faction: 'Black Eagles',
    Gender: 'M',
    RecruitReq: 'Need 10 Dexterity and C in Heavy Armor',
    BaseHp: '28',
    BaseStr: '8',
    BaseMag: '5',
    BaseDex: '6',
    BaseSpd: '8',
    BaseLuck: '6',
    BaseDef: '6',
    BaseRes: '2',
    BaseCha: '7',
    GrowthHP: '50',
    GrowthStr: '45',
    GrowthMag: '20',
    GrowthDex: '40',
    GrowthSpd: '50',
    GrowthLck: '40',
    GrowthDef: '35',
    GrowthRes: '20',
    GrowthCha: '40',
    MaxHp: '93',
    MaxStr: '64',
    MaxMag: '40',
    MaxDex: '56',
    MaxSpd: '70',
    MaxLuck: '56',
    MaxDef: '49',
    MaxRes: '36',
    MaxCha: '57',
    SwordProficiency: 'U',
    LanceProficiency: 'U',
    AxeProficiency: 'U',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: 'U',
    FlyingProficiency: '-',
    BaseSword: 'E+',
    BaseLance: 'D',
    BaseAxe: 'E+',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: 'D',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Cichol',
    Supports:
      'BylethM, BylethF, Edelgard, Hubert, Mercedes, Linhardt, Caspar, Bernadetta, Dorothea, Petra, Lorenz, Marianne, Hilda, Flayn, Manuela',
  },
  {
    ID: 'Bernadetta',
    Faction: 'Black Eagles',
    Gender: 'F',
    RecruitReq: 'Need 20 Strength and C in Bow',
    BaseHp: '25',
    BaseStr: '8',
    BaseMag: '5',
    BaseDex: '7',
    BaseSpd: '7',
    BaseLuck: '5',
    BaseDef: '4',
    BaseRes: '2',
    BaseCha: '6',
    GrowthHP: '35',
    GrowthStr: '35',
    GrowthMag: '20',
    GrowthDex: '55',
    GrowthSpd: '50',
    GrowthLck: '25',
    GrowthDef: '20',
    GrowthRes: '30',
    GrowthCha: '35',
    MaxHp: '70',
    MaxStr: '51',
    MaxMag: '40',
    MaxDex: '75',
    MaxSpd: '69',
    MaxLuck: '41',
    MaxDef: '41',
    MaxRes: '39',
    MaxCha: '49',
    SwordProficiency: 'D',
    LanceProficiency: 'U',
    AxeProficiency: 'D',
    BowProficiency: 'U',
    BrawlingProficiency: 'D',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: 'D',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: 'E+',
    BaseAxe: '-',
    BaseBow: 'D',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Indech',
    Supports:
      'BylethM, BylethF, Edelgard, Hubert, Ferdinand, Linhardt, Caspar, Dorothea, Petra, Felix, Sylvain, Ingrid, Raphael, Leonie, Seteth, Alois',
  },
  {
    ID: 'Caspar',
    Faction: 'Black Eagles',
    Gender: 'M',
    RecruitReq: 'Need 10 Strength and C in Brawling',
    BaseHp: '26',
    BaseStr: '9',
    BaseMag: '3',
    BaseDex: '5',
    BaseSpd: '6',
    BaseLuck: '8',
    BaseDef: '6',
    BaseRes: '2',
    BaseCha: '4',
    GrowthHP: '55',
    GrowthStr: '45',
    GrowthMag: '25',
    GrowthDex: '45',
    GrowthSpd: '45',
    GrowthLck: '40',
    GrowthDef: '30',
    GrowthRes: '20',
    GrowthCha: '25',
    MaxHp: '97',
    MaxStr: '65',
    MaxMag: '41',
    MaxDex: '61',
    MaxSpd: '62',
    MaxLuck: '58',
    MaxDef: '51',
    MaxRes: '35',
    MaxCha: '46',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: 'U',
    BowProficiency: 'D',
    BrawlingProficiency: 'U',
    ReasonProficiency: 'D',
    FaithProficiency: '-',
    AuthorityProficiency: 'D',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: 'D',
    BaseBow: '-',
    BaseBrawling: 'E+',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Edelgard, Hubert, Ferdinand, Linhardt, Bernadetta, Dorothea, Petra, Ashe, Annette, Raphael, Hilda, Shamir',
  },
  {
    ID: 'Petra',
    Faction: 'Black Eagles',
    Gender: 'F',
    RecruitReq: 'Need 10 Dexterity and C in Riding',
    BaseHp: '25',
    BaseStr: '9',
    BaseMag: '3',
    BaseDex: '7',
    BaseSpd: '10',
    BaseLuck: '7',
    BaseDef: '5',
    BaseRes: '2',
    BaseCha: '6',
    GrowthHP: '45',
    GrowthStr: '40',
    GrowthMag: '25',
    GrowthDex: '50',
    GrowthSpd: '60',
    GrowthLck: '45',
    GrowthDef: '30',
    GrowthRes: '15',
    GrowthCha: '35',
    MaxHp: '83',
    MaxStr: '59',
    MaxMag: '36',
    MaxDex: '69',
    MaxSpd: '85',
    MaxLuck: '63',
    MaxDef: '42',
    MaxRes: '35',
    MaxCha: '63',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: 'U',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: 'D',
    FaithProficiency: 'D',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: 'U',
    BaseSword: 'D+',
    BaseLance: '-',
    BaseAxe: 'E+',
    BaseBow: 'E+',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: 'D',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Edelgard, Claude, Hubert, Ferdinand, Linhardt, Caspar, Bernadetta, Dorothea, Ashe, Ignatz, Alois, Shamir, Cyril',
  },
  {
    ID: 'Linhardt',
    Faction: 'Black Eagles',
    Gender: 'M',
    RecruitReq: 'Need 10 Magic and C in Reason',
    BaseHp: '24',
    BaseStr: '5',
    BaseMag: '10',
    BaseDex: '6',
    BaseSpd: '5',
    BaseLuck: '7',
    BaseDef: '5',
    BaseRes: '9',
    BaseCha: '3',
    GrowthHP: '30',
    GrowthStr: '30',
    GrowthMag: '45',
    GrowthDex: '40',
    GrowthSpd: '40',
    GrowthLck: '45',
    GrowthDef: '30',
    GrowthRes: '45',
    GrowthCha: '20',
    MaxHp: '63',
    MaxStr: '42',
    MaxMag: '66',
    MaxDex: '56',
    MaxSpd: '55',
    MaxLuck: '63',
    MaxDef: '48',
    MaxRes: '65',
    MaxCha: '43',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: 'D',
    BowProficiency: '-',
    BrawlingProficiency: 'D',
    ReasonProficiency: 'U',
    FaithProficiency: 'U',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: 'E+',
    BaseFaith: 'D+',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Cethleann',
    Supports:
      'BylethM, BylethF, Edelgard, Hubert, Ferdinand, Caspar, Bernadetta, Dorothea, Petra, Annette, Lysithea, Marianne, Flayn, Hanneman, Catherine',
  },
  {
    ID: 'Dimitri',
    Faction: 'Blue Lions',
    Gender: 'M',
    RecruitReq: 'Blue Lions only',
    BaseHp: '28',
    BaseStr: '12',
    BaseMag: '4',
    BaseDex: '7',
    BaseSpd: '7',
    BaseLuck: '5',
    BaseDef: '7',
    BaseRes: '4',
    BaseCha: '9',
    GrowthHP: '55',
    GrowthStr: '60',
    GrowthMag: '20',
    GrowthDex: '50',
    GrowthSpd: '50',
    GrowthLck: '25',
    GrowthDef: '40',
    GrowthRes: '20',
    GrowthCha: '55',
    MaxHp: '99',
    MaxStr: '87',
    MaxMag: '38',
    MaxDex: '69',
    MaxSpd: '69',
    MaxLuck: '42',
    MaxDef: '57',
    MaxRes: '36',
    MaxCha: '77',
    SwordProficiency: 'U',
    LanceProficiency: 'U',
    AxeProficiency: 'D',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: 'D',
    FaithProficiency: '-',
    AuthorityProficiency: 'U',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: 'E+',
    BaseLance: 'D+',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'D',
    BaseArmor: '-',
    BaseRiding: 'D+',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Blaiddyd',
    Supports:
      'BylethM, BylethF, Marianne, Annette, Mercedes, Ingrid, Catherine, Flayn, Felix, Dedue, Gilbert, Sylvain, Raphael, Ashe, Alois',
  },
  {
    ID: 'Dedue',
    Faction: 'Blue Lions',
    Gender: 'M',
    RecruitReq: 'Blue Lions only',
    BaseHp: '30',
    BaseStr: '12',
    BaseMag: '2',
    BaseDex: '5',
    BaseSpd: '7',
    BaseLuck: '5',
    BaseDef: '8',
    BaseRes: '1',
    BaseCha: '4',
    GrowthHP: '60',
    GrowthStr: '50',
    GrowthMag: '15',
    GrowthDex: '30',
    GrowthSpd: '20',
    GrowthLck: '25',
    GrowthDef: '50',
    GrowthRes: '10',
    GrowthCha: '30',
    MaxHp: '108',
    MaxStr: '74',
    MaxMag: '30',
    MaxDex: '42',
    MaxSpd: '35',
    MaxLuck: '44',
    MaxDef: '70',
    MaxRes: '35',
    MaxCha: '41',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: 'U',
    BowProficiency: '-',
    BrawlingProficiency: 'U',
    ReasonProficiency: '-',
    FaithProficiency: 'D',
    AuthorityProficiency: '-',
    ArmorProficiency: 'U',
    RidingProficiency: 'D',
    FlyingProficiency: 'D',
    BaseSword: '-',
    BaseLance: 'E+',
    BaseAxe: 'D+',
    BaseBow: '-',
    BaseBrawling: 'E+',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: 'D',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Dimitri, Felix, Ashe, Sylvain, Mercedes, Annette, Ingrid, Flayn, Gilbert, Shamir',
  },
  {
    ID: 'Felix',
    Faction: 'Blue Lions',
    Gender: 'M',
    RecruitReq: 'Need 15 Speed and B+ in Sword',
    BaseHp: '26',
    BaseStr: '10',
    BaseMag: '5',
    BaseDex: '6',
    BaseSpd: '9',
    BaseLuck: '5',
    BaseDef: '5',
    BaseRes: '3',
    BaseCha: '5',
    GrowthHP: '45',
    GrowthStr: '55',
    GrowthMag: '30',
    GrowthDex: '45',
    GrowthSpd: '55',
    GrowthLck: '40',
    GrowthDef: '30',
    GrowthRes: '20',
    GrowthCha: '30',
    MaxHp: '84',
    MaxStr: '78',
    MaxMag: '42',
    MaxDex: '62',
    MaxSpd: '77',
    MaxLuck: '55',
    MaxDef: '51',
    MaxRes: '35',
    MaxCha: '42',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: 'U',
    BrawlingProficiency: 'U',
    ReasonProficiency: 'D',
    FaithProficiency: '-',
    AuthorityProficiency: 'D',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: 'D',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: 'E+',
    BaseBrawling: 'E+',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': 'Fraldarius',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Dimitri, Bernadetta, Dorothea, Dedue, Ashe, Sylvain, Mercedes, Annette, Ingrid, Lysithea, Leonie, Seteth, Flayn',
  },
  {
    ID: 'Mercedes',
    Faction: 'Blue Lions',
    Gender: 'F',
    RecruitReq: 'Need 15 Magic and C in Bow',
    BaseHp: '25',
    BaseStr: '6',
    BaseMag: '10',
    BaseDex: '6',
    BaseSpd: '8',
    BaseLuck: '5',
    BaseDef: '5',
    BaseRes: '9',
    BaseCha: '8',
    GrowthHP: '30',
    GrowthStr: '25',
    GrowthMag: '50',
    GrowthDex: '45',
    GrowthSpd: '40',
    GrowthLck: '30',
    GrowthDef: '25',
    GrowthRes: '45',
    GrowthCha: '40',
    MaxHp: '64',
    MaxStr: '37',
    MaxMag: '72',
    MaxDex: '62',
    MaxSpd: '58',
    MaxLuck: '54',
    MaxDef: '44',
    MaxRes: '65',
    MaxCha: '58',
    SwordProficiency: 'D',
    LanceProficiency: 'D',
    AxeProficiency: 'D',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: 'U',
    FaithProficiency: 'U',
    AuthorityProficiency: '-',
    ArmorProficiency: 'D',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: 'E+',
    BaseFaith: 'D',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Lamine',
    Supports:
      'BylethM, BylethF, Dimitri, Ferdinand, Dedue, Felix, Ashe, Sylvain, Annette, Ingrid, Lorenz, Ignatz, Hilda, Alois, Cyril',
  },
  {
    ID: 'Ashe',
    Faction: 'Blue Lions',
    Gender: 'M',
    RecruitReq: 'Need 15 Charm and C in Lance',
    BaseHp: '23',
    BaseStr: '8',
    BaseMag: '5',
    BaseDex: '8',
    BaseSpd: '9',
    BaseLuck: '6',
    BaseDef: '5',
    BaseRes: '6',
    BaseCha: '5',
    GrowthHP: '35',
    GrowthStr: '35',
    GrowthMag: '25',
    GrowthDex: '55',
    GrowthSpd: '50',
    GrowthLck: '40',
    GrowthDef: '20',
    GrowthRes: '35',
    GrowthCha: '25',
    MaxHp: '68',
    MaxStr: '51',
    MaxMag: '36',
    MaxDex: '76',
    MaxSpd: '71',
    MaxLuck: '56',
    MaxDef: '43',
    MaxRes: '49',
    MaxCha: '36',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: 'U',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: 'D',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: 'E+',
    BaseBow: 'D',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Dimitri, Caspar, Petra, Dedue, Felix, Sylvain, Mercedes, Annette, Ingrid, Marianne, Gilbert, Catherine, Cyril',
  },
  {
    ID: 'Annette',
    Faction: 'Blue Lions',
    Gender: 'F',
    RecruitReq: 'Need 10 Magic and B in Faith',
    BaseHp: '23',
    BaseStr: '6',
    BaseMag: '11',
    BaseDex: '7',
    BaseSpd: '7',
    BaseLuck: '6',
    BaseDef: '5',
    BaseRes: '4',
    BaseCha: '6',
    GrowthHP: '25',
    GrowthStr: '30',
    GrowthMag: '50',
    GrowthDex: '50',
    GrowthSpd: '35',
    GrowthLck: '35',
    GrowthDef: '20',
    GrowthRes: '30',
    GrowthCha: '35',
    MaxHp: '55',
    MaxStr: '43',
    MaxMag: '73',
    MaxDex: '69',
    MaxSpd: '50',
    MaxLuck: '49',
    MaxDef: '40',
    MaxRes: '41',
    MaxCha: '49',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: 'U',
    BowProficiency: 'D',
    BrawlingProficiency: '-',
    ReasonProficiency: 'U',
    FaithProficiency: '-',
    AuthorityProficiency: 'U',
    ArmorProficiency: 'D',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: 'E+',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: 'D+',
    BaseFaith: '-',
    BaseAuthority: 'E+',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Dominic',
    Supports:
      'BylethM, BylethF, Dimitri, Claude, Linhardt, Caspar, Dedue, Felix, Ashe, Sylvain, Mercedes, Ingrid, Hilda, Hanneman, Gilbert, Lysithea',
  },
  {
    ID: 'Sylvain',
    Faction: 'Blue Lions',
    Gender: 'M',
    RecruitReq:
      'Need 25 Charm and C in Reason (If protagonist is female, automatically joins)',
    BaseHp: '27',
    BaseStr: '9',
    BaseMag: '5',
    BaseDex: '5',
    BaseSpd: '8',
    BaseLuck: '6',
    BaseDef: '6',
    BaseRes: '2',
    BaseCha: '7',
    GrowthHP: '55',
    GrowthStr: '45',
    GrowthMag: '30',
    GrowthDex: '35',
    GrowthSpd: '50',
    GrowthLck: '35',
    GrowthDef: '40',
    GrowthRes: '25',
    GrowthCha: '40',
    MaxHp: '98',
    MaxStr: '65',
    MaxMag: '42',
    MaxDex: '48',
    MaxSpd: '70',
    MaxLuck: '49',
    MaxDef: '56',
    MaxRes: '38',
    MaxCha: '57',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: 'U',
    BowProficiency: 'D',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: 'U',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: 'D',
    BaseAxe: 'D',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: 'D',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Gautier',
    Supports:
      'BylethM, BylethF, Dimitri, Dedue, Felix, Ashe, Mercedes, Annette, Ingrid, Bernadetta, Dorothea, Lorenz, Lysithea, Marianne, Hilda, Leonie, Flayn, Manuela',
  },
  {
    ID: 'Ingrid',
    Faction: 'Blue Lions',
    Gender: 'F',
    RecruitReq: 'Need 15 Dexterity and D in Flying',
    BaseHp: '27',
    BaseStr: '8',
    BaseMag: '6',
    BaseDex: '6',
    BaseSpd: '8',
    BaseLuck: '6',
    BaseDef: '5',
    BaseRes: '8',
    BaseCha: '8',
    GrowthHP: '40',
    GrowthStr: '35',
    GrowthMag: '35',
    GrowthDex: '40',
    GrowthSpd: '60',
    GrowthLck: '45',
    GrowthDef: '30',
    GrowthRes: '40',
    GrowthCha: '45',
    MaxHp: '79',
    MaxStr: '51',
    MaxMag: '49',
    MaxDex: '56',
    MaxSpd: '83',
    MaxLuck: '62',
    MaxDef: '51',
    MaxRes: '58',
    MaxCha: '64',
    SwordProficiency: 'U',
    LanceProficiency: 'U',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: 'U',
    FlyingProficiency: 'U',
    BaseSword: 'E+',
    BaseLance: 'D',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: 'D',
    BaseFlying: 'D',
    'Major Crest': '-',
    'Minor Crest': 'Daphnel',
    Supports:
      'BylethM, BylethF, Dimitri, Claude, Bernadetta, Dorothea, Dedue, Felix, Ashe, Sylvain, Mercedes, Annette, Raphael, Ignatz, Seteth, Catherine',
  },
  {
    ID: 'Claude',
    Faction: 'Golden Deers',
    Gender: 'M',
    RecruitReq: 'Golden Deer only',
    BaseHp: '26',
    BaseStr: '11',
    BaseMag: '5',
    BaseDex: '8',
    BaseSpd: '8',
    BaseLuck: '7',
    BaseDef: '6',
    BaseRes: '4',
    BaseCha: '8',
    GrowthHP: '35',
    GrowthStr: '40',
    GrowthMag: '25',
    GrowthDex: '60',
    GrowthSpd: '55',
    GrowthLck: '45',
    GrowthDef: '30',
    GrowthRes: '25',
    GrowthCha: '55',
    MaxHp: '71',
    MaxStr: '61',
    MaxMag: '40',
    MaxDex: '89',
    MaxSpd: '76',
    MaxLuck: '63',
    MaxDef: '50',
    MaxRes: '42',
    MaxCha: '76',
    SwordProficiency: 'U',
    LanceProficiency: 'D',
    AxeProficiency: '-',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: 'D',
    AuthorityProficiency: 'U',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: 'U',
    BaseSword: 'E+',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: 'D',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'D',
    BaseArmor: '-',
    BaseRiding: 'E+',
    BaseFlying: 'E+',
    'Major Crest': '-',
    'Minor Crest': 'Riegan',
    Supports:
      'BylethM, BylethF, Petra, Annette, Ingrid, Lorenz, Raphael, Ignatz, Lysithea, Marianne, Hilda, Leonie, Flayn, Shamir, Cyril',
  },
  {
    ID: 'Lorenz',
    Faction: 'Golden Deers',
    Gender: 'M',
    RecruitReq: 'Need 20 Charm and C in Reason',
    BaseHp: '28',
    BaseStr: '8',
    BaseMag: '7',
    BaseDex: '6',
    BaseSpd: '7',
    BaseLuck: '5',
    BaseDef: '6',
    BaseRes: '6',
    BaseCha: '3',
    GrowthHP: '55',
    GrowthStr: '40',
    GrowthMag: '40',
    GrowthDex: '45',
    GrowthSpd: '40',
    GrowthLck: '25',
    GrowthDef: '30',
    GrowthRes: '40',
    GrowthCha: '35',
    MaxHp: '99',
    MaxStr: '58',
    MaxMag: '57',
    MaxDex: '62',
    MaxSpd: '57',
    MaxLuck: '48',
    MaxDef: '55',
    MaxRes: '56',
    MaxCha: '46',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: 'D',
    ReasonProficiency: 'U',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '',
    RidingProficiency: 'U',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: 'D',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: 'E+',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: 'D',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Gloucester',
    Supports:
      'BylethM, BylethF, Claude, Raphael, Ignatz, Lysithea, Marianne, Hilda, Leonie, Ferdinand, Dorothea, Sylvain, Mercedes, Manuela',
  },
  {
    ID: 'Hilda',
    Faction: 'Golden Deers',
    Gender: 'F',
    RecruitReq:
      'Need 30 Charm and C in Axe, not recruitable if you choose to oppose the church',
    BaseHp: '29',
    BaseStr: '10',
    BaseMag: '5',
    BaseDex: '5',
    BaseSpd: '8',
    BaseLuck: '6',
    BaseDef: '6',
    BaseRes: '3',
    BaseCha: '7',
    GrowthHP: '50',
    GrowthStr: '45',
    GrowthMag: '25',
    GrowthDex: '30',
    GrowthSpd: '50',
    GrowthLck: '35',
    GrowthDef: '35',
    GrowthRes: '20',
    GrowthCha: '50',
    MaxHp: '94',
    MaxStr: '66',
    MaxMag: '36',
    MaxDex: '42',
    MaxSpd: '70',
    MaxLuck: '49',
    MaxDef: '49',
    MaxRes: '39',
    MaxCha: '76',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: 'U',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: 'D',
    AuthorityProficiency: 'D',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: 'E+',
    BaseAxe: 'D',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Goneril',
    Supports:
      'BylethM, BylethF, Claude, Lorenz, Raphael, Ignatz, Lysithea, Marianne, Leonie, Ferdinand, Caspar, Sylvain, Mercedes, Annette, Seteth, Cyril',
  },
  {
    ID: 'Raphael',
    Faction: 'Golden Deers',
    Gender: 'M',
    RecruitReq: 'Need 20 Strength and C in Heavy Armor',
    BaseHp: '30',
    BaseStr: '11',
    BaseMag: '3',
    BaseDex: '5',
    BaseSpd: '6',
    BaseLuck: '6',
    BaseDef: '7',
    BaseRes: '1',
    BaseCha: '4',
    GrowthHP: '65',
    GrowthStr: '50',
    GrowthMag: '15',
    GrowthDex: '35',
    GrowthSpd: '15',
    GrowthLck: '35',
    GrowthDef: '45',
    GrowthRes: '10',
    GrowthCha: '25',
    MaxHp: '114',
    MaxStr: '73',
    MaxMag: '31',
    MaxDex: '48',
    MaxSpd: '33',
    MaxLuck: '49',
    MaxDef: '63',
    MaxRes: '36',
    MaxCha: '51',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: 'U',
    BowProficiency: 'D',
    BrawlingProficiency: 'U',
    ReasonProficiency: 'D',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: 'U',
    RidingProficiency: 'D',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: 'E+',
    BaseBow: '-',
    BaseBrawling: 'D',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: 'D',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Dimitri, Claude, Caspar, Bernadetta, Ingrid, Lorenz, Ignatz, Lysithea, Marianne, Hilda, Leonie, Flayn, Shamir',
  },
  {
    ID: 'Lysithea',
    Faction: 'Golden Deers',
    Gender: 'F',
    RecruitReq: 'Need 15 Magic and B in Faith',
    BaseHp: '22',
    BaseStr: '4',
    BaseMag: '11',
    BaseDex: '7',
    BaseSpd: '7',
    BaseLuck: '4',
    BaseDef: '3',
    BaseRes: '4',
    BaseCha: '5',
    GrowthHP: '20',
    GrowthStr: '15',
    GrowthMag: '60',
    GrowthDex: '60',
    GrowthSpd: '50',
    GrowthLck: '15',
    GrowthDef: '10',
    GrowthRes: '25',
    GrowthCha: '25',
    MaxHp: '48',
    MaxStr: '30',
    MaxMag: '86',
    MaxDex: '82',
    MaxSpd: '69',
    MaxLuck: '40',
    MaxDef: '36',
    MaxRes: '41',
    MaxCha: '44',
    SwordProficiency: 'D',
    LanceProficiency: 'D',
    AxeProficiency: 'D',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: 'U',
    FaithProficiency: 'U',
    AuthorityProficiency: 'U',
    ArmorProficiency: 'D',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: 'D',
    BaseFaith: 'E+',
    BaseAuthority: 'E+',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': 'Gloucester',
    'Minor Crest': 'Charon',
    Supports:
      'BylethM, BylethF, Edelgard, Claude, Linhardt, Felix, Sylvain, Annette, Lorenz, Raphael, Ignatz, Marianne, Hilda, Leonie, Hanneman, Catherine, Cyril',
  },
  {
    ID: 'Ignatz',
    Faction: 'Golden Deers',
    Gender: 'M',
    RecruitReq: 'Need 10 Dexterity and B in Authority',
    BaseHp: '25',
    BaseStr: '8',
    BaseMag: '5',
    BaseDex: '7',
    BaseSpd: '8',
    BaseLuck: '8',
    BaseDef: '4',
    BaseRes: '6',
    BaseCha: '4',
    GrowthHP: '35',
    GrowthStr: '35',
    GrowthMag: '30',
    GrowthDex: '50',
    GrowthSpd: '50',
    GrowthLck: '55',
    GrowthDef: '25',
    GrowthRes: '35',
    GrowthCha: '25',
    MaxHp: '70',
    MaxStr: '51',
    MaxMag: '42',
    MaxDex: '69',
    MaxSpd: '70',
    MaxLuck: '76',
    MaxDef: '43',
    MaxRes: '49',
    MaxCha: '45',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: 'U',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: 'D',
    BaseSword: 'E+',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: 'D',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'E+',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Claude, Lorenz, Raphael, Lysithea, Marianne, Hilda, Leonie, Petra, Mercedes, Ingrid, Flayn, Shamir, Cyril',
  },
  {
    ID: 'Marianne',
    Faction: 'Golden Deers',
    Gender: 'F',
    RecruitReq: 'Need 10 Magic and C in Riding',
    BaseHp: '23',
    BaseStr: '5',
    BaseMag: '11',
    BaseDex: '6',
    BaseSpd: '7',
    BaseLuck: '6',
    BaseDef: '4',
    BaseRes: '8',
    BaseCha: '7',
    GrowthHP: '35',
    GrowthStr: '20',
    GrowthMag: '50',
    GrowthDex: '40',
    GrowthSpd: '40',
    GrowthLck: '35',
    GrowthDef: '15',
    GrowthRes: '45',
    GrowthCha: '40',
    MaxHp: '68',
    MaxStr: '30',
    MaxMag: '73',
    MaxDex: '56',
    MaxSpd: '57',
    MaxLuck: '49',
    MaxDef: '39',
    MaxRes: '64',
    MaxCha: '57',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: 'D',
    ReasonProficiency: '-',
    FaithProficiency: 'U',
    AuthorityProficiency: '-',
    ArmorProficiency: 'D',
    RidingProficiency: 'U',
    FlyingProficiency: 'U',
    BaseSword: 'E+',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: 'D+',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'The Beast',
    Supports:
      'BylethM, BylethF, Dimitri, Claude, Ferdinand, Linhardt, Ashe, Sylvain, Lorenz, Raphael, Ignatz, Lysithea, Hilda, Leonie, Hanneman',
  },
  {
    ID: 'Leonie',
    Faction: 'Golden Deers',
    Gender: 'F',
    RecruitReq: 'Need 15 Strength and C in Lance',
    BaseHp: '26',
    BaseStr: '9',
    BaseMag: '5',
    BaseDex: '8',
    BaseSpd: '9',
    BaseLuck: '6',
    BaseDef: '7',
    BaseRes: '2',
    BaseCha: '7',
    GrowthHP: '40',
    GrowthStr: '40',
    GrowthMag: '20',
    GrowthDex: '55',
    GrowthSpd: '60',
    GrowthLck: '40',
    GrowthDef: '40',
    GrowthRes: '15',
    GrowthCha: '40',
    MaxHp: '78',
    MaxStr: '59',
    MaxMag: '38',
    MaxDex: '76',
    MaxSpd: '84',
    MaxLuck: '56',
    MaxDef: '57',
    MaxRes: '36',
    MaxCha: '57',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: '-',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: 'U',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: 'D+',
    BaseAxe: '-',
    BaseBow: 'E+',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: 'E+',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Claude, Lorenz, Raphael, Ignatz, Lysithea, Marianne, Hilda, Bernadetta, Felix, Sylvain, Seteth, Alois, Shamir',
  },
  {
    ID: 'Manuela',
    Faction: 'Church of Seiros',
    Gender: 'F',
    RecruitReq: 'Need to be Level 15, from chapter 8',
    BaseHp: '26',
    BaseStr: '10',
    BaseMag: '8',
    BaseDex: '6',
    BaseSpd: '8',
    BaseLuck: '6',
    BaseDef: '5',
    BaseRes: '4',
    BaseCha: '7',
    GrowthHP: '50',
    GrowthStr: '35',
    GrowthMag: '35',
    GrowthDex: '40',
    GrowthSpd: '60',
    GrowthLck: '35',
    GrowthDef: '30',
    GrowthRes: '25',
    GrowthCha: '50',
    MaxHp: '91',
    MaxStr: '53',
    MaxMag: '48',
    MaxDex: '56',
    MaxSpd: '83',
    MaxLuck: '52',
    MaxDef: '42',
    MaxRes: '44',
    MaxCha: '69',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: 'D',
    FaithProficiency: 'U',
    AuthorityProficiency: '-',
    ArmorProficiency: 'D',
    RidingProficiency: '-',
    FlyingProficiency: 'U',
    BaseSword: 'D',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: 'C',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: 'D',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Edelgard, Ferdinand, Dorothea, Sylvain, Lorenz, Seteth, Flayn, Hanneman, Gilbert, Alois, Cyril',
  },
  {
    ID: 'Hanneman',
    Faction: 'Church of Seiros',
    Gender: 'M',
    RecruitReq: 'Need to be Level 15, from chapter 8',
    BaseHp: '25',
    BaseStr: '6',
    BaseMag: '10',
    BaseDex: '6',
    BaseSpd: '6',
    BaseLuck: '4',
    BaseDef: '5',
    BaseRes: '7',
    BaseCha: '5',
    GrowthHP: '40',
    GrowthStr: '30',
    GrowthMag: '55',
    GrowthDex: '45',
    GrowthSpd: '20',
    GrowthLck: '35',
    GrowthDef: '25',
    GrowthRes: '40',
    GrowthCha: '35',
    MaxHp: '77',
    MaxStr: '43',
    MaxMag: '78',
    MaxDex: '62',
    MaxSpd: '35',
    MaxLuck: '49',
    MaxDef: '36',
    MaxRes: '57',
    MaxCha: '48',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: 'U',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: 'D',
    RidingProficiency: 'U',
    FlyingProficiency: 'D',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: 'D',
    BaseBrawling: '-',
    BaseReason: 'C',
    BaseFaith: '-',
    BaseAuthority: 'D',
    BaseArmor: '-',
    BaseRiding: 'D',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Indech',
    Supports:
      'BylethM, BylethF, Edelgard, Hubert, Linhardt, Manuela, Dorothea, Annette, Lysithea, Marianne, Seteth, Gilbert, Alois',
  },
  {
    ID: 'Seteth',
    Faction: 'Church of Seiros',
    Gender: 'M',
    RecruitReq:
      'Joins automatically during chapter 12, not recruitable if you choose to oppose the church',
    BaseHp: '27',
    BaseStr: '9',
    BaseMag: '8',
    BaseDex: '8',
    BaseSpd: '5',
    BaseLuck: '6',
    BaseDef: '6',
    BaseRes: '4',
    BaseCha: '9',
    GrowthHP: '50',
    GrowthStr: '45',
    GrowthMag: '35',
    GrowthDex: '50',
    GrowthSpd: '50',
    GrowthLck: '25',
    GrowthDef: '30',
    GrowthRes: '25',
    GrowthCha: '45',
    MaxHp: '92',
    MaxStr: '65',
    MaxMag: '51',
    MaxDex: '70',
    MaxSpd: '67',
    MaxLuck: '49',
    MaxDef: '43',
    MaxRes: '41',
    MaxCha: '65',
    SwordProficiency: 'U',
    LanceProficiency: 'U',
    AxeProficiency: 'U',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: 'U',
    ArmorProficiency: '-',
    RidingProficiency: 'D',
    FlyingProficiency: 'U',
    BaseSword: 'D+',
    BaseLance: 'C',
    BaseAxe: 'C',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'C',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: 'C',
    'Major Crest': 'Cichol',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Bernadetta, Felix, Ingrid, Hilda, Leonie, Flayn, Hanneman, Manuela, Catherine, Cyril',
  },
  {
    ID: 'Flayn',
    Faction: 'Church of Seiros',
    Gender: 'F',
    RecruitReq: 'Joins automatically at start of chapter 7',
    BaseHp: '24',
    BaseStr: '6',
    BaseMag: '9',
    BaseDex: '6',
    BaseSpd: '5',
    BaseLuck: '4',
    BaseDef: '5',
    BaseRes: '10',
    BaseCha: '9',
    GrowthHP: '25',
    GrowthStr: '25',
    GrowthMag: '55',
    GrowthDex: '45',
    GrowthSpd: '35',
    GrowthLck: '15',
    GrowthDef: '25',
    GrowthRes: '50',
    GrowthCha: '45',
    MaxHp: '56',
    MaxStr: '37',
    MaxMag: '77',
    MaxDex: '62',
    MaxSpd: '48',
    MaxLuck: '46',
    MaxDef: '36',
    MaxRes: '72',
    MaxCha: '65',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: 'U',
    AuthorityProficiency: '-',
    ArmorProficiency: 'D',
    RidingProficiency: 'D',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: 'E+',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: 'D+',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: 'D',
    'Major Crest': 'Cethleann',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Ferdinand, Linhardt, Dimitri, Dedue, Felix, Sylvain, Claude, Raphael, Ignatz, Seteth, Manuela',
  },
  {
    ID: 'Cyril',
    Faction: 'Church of Seiros',
    Gender: 'M',
    RecruitReq: 'Need to be Level 10, from chapter 5',
    BaseHp: '24',
    BaseStr: '7',
    BaseMag: '4',
    BaseDex: '6',
    BaseSpd: '6',
    BaseLuck: '6',
    BaseDef: '5',
    BaseRes: '2',
    BaseCha: '4',
    GrowthHP: '35',
    GrowthStr: '20',
    GrowthMag: '15',
    GrowthDex: '40',
    GrowthSpd: '40',
    GrowthLck: '30',
    GrowthDef: '10',
    GrowthRes: '10',
    GrowthCha: '15',
    MaxHp: '85',
    MaxStr: '55',
    MaxMag: '48',
    MaxDex: '78',
    MaxSpd: '76',
    MaxLuck: '66',
    MaxDef: '45',
    MaxRes: '41',
    MaxCha: '48',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: 'U',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: 'D',
    FaithProficiency: 'D',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: 'U',
    FlyingProficiency: 'U',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: 'D+',
    BaseBow: 'D',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Petra, Ashe, Mercedes, Claude, Ignatz, Lysithea, Hilda, Seteth, Manuela, Shamir',
  },
  {
    ID: 'Catherine',
    Faction: 'Church of Seiros',
    Gender: 'F',
    RecruitReq:
      'Need to be Level 15, from chapter 4, not recruitable if you choose to oppose the church',
    BaseHp: '27',
    BaseStr: '8',
    BaseMag: '5',
    BaseDex: '6',
    BaseSpd: '7',
    BaseLuck: '6',
    BaseDef: '5',
    BaseRes: '2',
    BaseCha: '4',
    GrowthHP: '50',
    GrowthStr: '50',
    GrowthMag: '25',
    GrowthDex: '40',
    GrowthSpd: '55',
    GrowthLck: '30',
    GrowthDef: '30',
    GrowthRes: '20',
    GrowthCha: '25',
    MaxHp: '92',
    MaxStr: '70',
    MaxMag: '36',
    MaxDex: '56',
    MaxSpd: '75',
    MaxLuck: '43',
    MaxDef: '42',
    MaxRes: '37',
    MaxCha: '35',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: 'U',
    ReasonProficiency: 'D',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: 'B',
    BaseLance: '-',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: 'D+',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'D',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': 'Charon',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Linhardt, Caspar, Dimitri, Ashe, Ingrid, Lorenz, Lysithea, Leonie, Seteth, Gilbert, Alois, Shamir',
  },
  {
    ID: 'Alois',
    Faction: 'Church of Seiros',
    Gender: 'M',
    RecruitReq: 'Need to be Level 15, from chapter 11',
    BaseHp: '28',
    BaseStr: '9',
    BaseMag: '4',
    BaseDex: '5',
    BaseSpd: '6',
    BaseLuck: '5',
    BaseDef: '5',
    BaseRes: '2',
    BaseCha: '7',
    GrowthHP: '45',
    GrowthStr: '45',
    GrowthMag: '20',
    GrowthDex: '35',
    GrowthSpd: '40',
    GrowthLck: '30',
    GrowthDef: '40',
    GrowthRes: '20',
    GrowthCha: '40',
    MaxHp: '86',
    MaxStr: '71',
    MaxMag: '33',
    MaxDex: '48',
    MaxSpd: '56',
    MaxLuck: '42',
    MaxDef: '55',
    MaxRes: '37',
    MaxCha: '57',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: 'U',
    BowProficiency: '-',
    BrawlingProficiency: 'U',
    ReasonProficiency: 'D',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: 'U',
    RidingProficiency: '-',
    FlyingProficiency: 'D',
    BaseSword: '-',
    BaseLance: '-',
    BaseAxe: 'C',
    BaseBow: '-',
    BaseBrawling: 'D+',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'C',
    BaseArmor: 'C',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Bernadetta, Petra, Dimitri, Mercedes, Leonie, Hanneman, Manuela, Gilbert, Catherine, Shamir',
  },
  {
    ID: 'Gilbert',
    Faction: 'Church of Seiros',
    Gender: 'M',
    RecruitReq: 'During chapter 13 with Blue Lions only',
    BaseHp: '30',
    BaseStr: '9',
    BaseMag: '4',
    BaseDex: '6',
    BaseSpd: '5',
    BaseLuck: '4',
    BaseDef: '5',
    BaseRes: '2',
    BaseCha: '6',
    GrowthHP: '55',
    GrowthStr: '45',
    GrowthMag: '20',
    GrowthDex: '45',
    GrowthSpd: '30',
    GrowthLck: '15',
    GrowthDef: '45',
    GrowthRes: '10',
    GrowthCha: '35',
    MaxHp: '101',
    MaxStr: '65',
    MaxMag: '35',
    MaxDex: '62',
    MaxSpd: '42',
    MaxLuck: '40',
    MaxDef: '61',
    MaxRes: '35',
    MaxCha: '49',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: 'U',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: 'U',
    RidingProficiency: 'U',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: 'C',
    BaseAxe: 'C',
    BaseBow: '-',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'D+',
    BaseArmor: 'D',
    BaseRiding: 'C',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Dimitri, Dedue, Ashe, Annette, Hanneman, Manuela, Alois, Catherine',
  },
  {
    ID: 'Shamir',
    Faction: 'Church of Seiros',
    Gender: 'F',
    RecruitReq: 'At level 15 or higher, from chapter 6',
    BaseHp: '26',
    BaseStr: '8',
    BaseMag: '4',
    BaseDex: '7',
    BaseSpd: '6',
    BaseLuck: '8',
    BaseDef: '5',
    BaseRes: '2',
    BaseCha: '6',
    GrowthHP: '35',
    GrowthStr: '40',
    GrowthMag: '20',
    GrowthDex: '55',
    GrowthSpd: '40',
    GrowthLck: '55',
    GrowthDef: '20',
    GrowthRes: '15',
    GrowthCha: '30',
    MaxHp: '71',
    MaxStr: '58',
    MaxMag: '35',
    MaxDex: '75',
    MaxSpd: '56',
    MaxLuck: '76',
    MaxDef: '37',
    MaxRes: '35',
    MaxCha: '43',
    SwordProficiency: '-',
    LanceProficiency: 'U',
    AxeProficiency: '-',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: 'D',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: '-',
    BaseLance: 'D+',
    BaseAxe: '-',
    BaseBow: 'B',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'D',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': '-',
    Supports:
      'BylethM, BylethF, Hubert, Caspar, Petra, Dedue, Claude, Raphael, Ignatz, Leonie, Alois, Catherine, Cyril',
  },
  {
    ID: 'Jeritza',
    Faction: 'Church of Seiros',
    Gender: 'M',
    RecruitReq:
      'DLC only, at start of chapter 13 only if you choose to oppose the church',
    BaseHp: '30',
    BaseStr: '8',
    BaseMag: '6',
    BaseDex: '6',
    BaseSpd: '8',
    BaseLuck: '4',
    BaseDef: '7',
    BaseRes: '5',
    BaseCha: '3',
    GrowthHP: '50',
    GrowthStr: '50',
    GrowthMag: '35',
    GrowthDex: '35',
    GrowthSpd: '60',
    GrowthLck: '30',
    GrowthDef: '40',
    GrowthRes: '25',
    GrowthCha: '25',
    MaxHp: '79',
    MaxStr: '74',
    MaxMag: '42',
    MaxDex: '49',
    MaxSpd: '78',
    MaxLuck: '41',
    MaxDef: '63',
    MaxRes: '42',
    MaxCha: '42',
    SwordProficiency: 'U',
    LanceProficiency: 'U',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: 'U',
    ReasonProficiency: '-',
    FaithProficiency: 'D',
    AuthorityProficiency: 'D',
    ArmorProficiency: '-',
    RidingProficiency: 'U',
    FlyingProficiency: '-',
    BaseSword: 'B',
    BaseLance: 'A',
    BaseAxe: '-',
    BaseBow: '-',
    BaseBrawling: 'D+',
    BaseReason: '-',
    BaseFaith: '-',
    BaseAuthority: 'B',
    BaseArmor: '-',
    BaseRiding: 'B',
    BaseFlying: '-',
    'Major Crest': '-',
    'Minor Crest': 'Lamine',
    Supports: 'BylethM, BylethF,Mercedes',
  },
  {
    ID: 'Anna',
    Faction: 'Church of Seiros',
    Gender: 'F',
    RecruitReq: 'DLC only, from chapter 3',
    BaseHp: '26',
    BaseStr: '7',
    BaseMag: '7',
    BaseDex: '7',
    BaseSpd: '7',
    BaseLuck: '7',
    BaseDef: '5',
    BaseRes: '7',
    BaseCha: '7',
    GrowthHP: '35',
    GrowthStr: '35',
    GrowthMag: '35',
    GrowthDex: '45',
    GrowthSpd: '55',
    GrowthLck: '45',
    GrowthDef: '30',
    GrowthRes: '40',
    GrowthCha: '50',
    MaxHp: '68',
    MaxStr: '55',
    MaxMag: '49',
    MaxDex: '76',
    MaxSpd: '65',
    MaxLuck: '75',
    MaxDef: '44',
    MaxRes: '49',
    MaxCha: '60',
    SwordProficiency: 'U',
    LanceProficiency: '-',
    AxeProficiency: 'U',
    BowProficiency: 'U',
    BrawlingProficiency: '-',
    ReasonProficiency: 'D',
    FaithProficiency: 'U',
    AuthorityProficiency: 'D',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    BaseSword: 'D',
    BaseLance: '-',
    BaseAxe: 'E+',
    BaseBow: 'E+',
    BaseBrawling: '-',
    BaseReason: '-',
    BaseFaith: 'E+',
    BaseAuthority: '-',
    BaseArmor: '-',
    BaseRiding: '-',
    BaseFlying: '-',
    'Major Crest': 'Ernest',
    'Minor Crest': '-',
    Supports: '',
  },
];
