const data = {
  dancer: {
    id: 0,
    code: 'dancer',
    name: 'Dancer',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: [''],
    unitType: ['magic'],
    fromSeasonPass: false,
  },
  swordmaster: {
    id: 1,
    code: 'swordmaster',
    name: 'Swordmaster',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['sword'],
    unitType: [''],
    fromSeasonPass: false,
  },
  assassin: {
    id: 2,
    code: 'assassin',
    name: 'Assassin',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['sword', 'bow'],
    unitType: [''],
    fromSeasonPass: false,
  },
  fortressknight: {
    id: 3,
    code: 'fortressknight',
    name: 'Fortress Knight',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['axe', 'armor'],
    unitType: ['armor'],
    fromSeasonPass: false,
  },
  enlightenedone: {
    id: 4,
    code: 'enlightenedone',
    name: 'Enlightened One',
    exclusiveTo: ['bylethm', 'bylethf'],
    requiredGender: ['male', 'female'],
    requiredSkills: [''],
    unitType: ['magic'],
    fromSeasonPass: false,
  },
  emperor: {
    id: 5,
    code: 'emperor',
    name: 'Emperor',
    exclusiveTo: ['edelgard'],
    requiredGender: ['male', 'female'],
    requiredSkills: [''],
    unitType: ['armor'],
    fromSeasonPass: false,
  },
  greatlord: {
    id: 6,
    code: 'greatlord',
    name: 'Great Lord',
    exclusiveTo: ['dimitri'],
    requiredGender: ['male', 'female'],
    requiredSkills: [''],
    unitType: [''],
    fromSeasonPass: false,
  },
  barbarossa: {
    id: 7,
    code: 'barbarossa',
    name: 'Barbarossa',
    exclusiveTo: ['claude'],
    requiredGender: ['male', 'female'],
    requiredSkills: [''],
    unitType: ['flying'],
    fromSeasonPass: false,
  },
  falconknight: {
    id: 8,
    code: 'falconknight',
    name: 'Falcon Knight',
    exclusiveTo: [''],
    requiredGender: ['female'],
    requiredSkills: ['sword', 'lance', ' flying'],
    unitType: ['flying'],
    fromSeasonPass: false,
  },
  wyvernlord: {
    id: 9,
    code: 'wyvernlord',
    name: 'Wyvern Lord',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['lance', 'axe', ' flying'],
    unitType: ['flying'],
    fromSeasonPass: false,
  },
  mortalsavant: {
    id: 10,
    code: 'mortalsavant',
    name: 'Mortal Savant',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['sword', 'reason'],
    unitType: ['magic'],
    fromSeasonPass: false,
  },
  greatknight: {
    id: 11,
    code: 'greatknight',
    name: 'Great Knight',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['axe', 'armor', ' riding'],
    unitType: ['riding', 'armor'],
    fromSeasonPass: false,
  },
  bowknight: {
    id: 12,
    code: 'bowknight',
    name: 'Bow Knight',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['lance', 'bow', ' riding'],
    unitType: ['riding'],
    fromSeasonPass: false,
  },
  darkknight: {
    id: 13,
    code: 'darkknight',
    name: 'Dark Knight',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['lance', 'reason', ' riding'],
    unitType: ['riding', 'magic'],
    fromSeasonPass: false,
  },
  holyknight: {
    id: 14,
    code: 'holyknight',
    name: 'Holy Knight',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['lance', 'faith', ' riding'],
    unitType: ['riding', 'magic'],
    fromSeasonPass: false,
  },
  warmaster: {
    id: 15,
    code: 'warmaster',
    name: 'War Master',
    exclusiveTo: [''],
    requiredGender: ['male'],
    requiredSkills: ['axe', 'brawling'],
    unitType: [''],
    fromSeasonPass: false,
  },
  gremory: {
    id: 16,
    code: 'gremory',
    name: 'Gremory',
    exclusiveTo: [''],
    requiredGender: ['female'],
    requiredSkills: ['reason', 'faith'],
    unitType: ['magic'],
    fromSeasonPass: false,
  },
  trickster: {
    id: 17,
    code: 'trickster',
    name: 'Trickster',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['sword', 'faith'],
    unitType: ['magic'],
    fromSeasonPass: false,
  },
  warmonk: {
    id: 18,
    code: 'warmonk',
    name: 'War Monk',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['brawling', 'faith'],
    unitType: ['magic'],
    fromSeasonPass: false,
  },
  darkflier: {
    id: 19,
    code: 'darkflier',
    name: 'Dark Flier',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['reason', 'flying'],
    unitType: ['flying', 'magic'],
    fromSeasonPass: false,
  },
  valkyrie: {
    id: 20,
    code: 'valkyrie',
    name: 'Valkyrie',
    exclusiveTo: [''],
    requiredGender: ['male', 'female'],
    requiredSkills: ['reason', 'riding'],
    unitType: ['riding', 'magic'],
    fromSeasonPass: false,
  },
};
