const data = [
  {
    ID: 'Dancer',
    ReqLevel: '0',
    ReqSkill: '',
    ReqRank: '',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Magic',
    SwordProficiency: '2',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '2',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '20',
    GrowthStr: '-5',
    GrowthMag: '-',
    GrowthDex: '-',
    GrowthSpd: '-',
    GrowthLck: '-',
    GrowthDef: '-5',
    GrowthRes: '-5',
    GrowthCha: '10',
    Movement: '4',
    '': '',
  },
  {
    ID: 'Swordmaster',
    ReqLevel: '20',
    ReqSkill: 'Sword',
    ReqRank: 'A',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: '',
    SwordProficiency: '3',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '25',
    GrowthStr: '10',
    GrowthMag: '-',
    GrowthDex: '-',
    GrowthSpd: '20',
    GrowthLck: '-',
    GrowthDef: '-',
    GrowthRes: '-5',
    GrowthCha: '5',
    Movement: '5',
    '': '55',
  },
  {
    ID: 'Assassin',
    ReqLevel: '20',
    ReqSkill: 'Sword, Bow',
    ReqRank: 'B, C',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: '',
    SwordProficiency: '3',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '2',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '20',
    GrowthStr: '-',
    GrowthMag: '-',
    GrowthDex: '20',
    GrowthSpd: '20',
    GrowthLck: '-',
    GrowthDef: '-',
    GrowthRes: '-',
    GrowthCha: '-',
    Movement: '6',
    '': '',
  },
  {
    ID: 'Fortress Knight',
    ReqLevel: '20',
    ReqSkill: 'Axe, Armor',
    ReqRank: 'B, B',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Armor',
    SwordProficiency: '-',
    LanceProficiency: '2',
    AxeProficiency: '3',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '3',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '30',
    GrowthStr: '10',
    GrowthMag: '-',
    GrowthDex: '-',
    GrowthSpd: '-10',
    GrowthLck: '-',
    GrowthDef: '15',
    GrowthRes: '-',
    GrowthCha: '5',
    Movement: '4',
    '': '',
  },
  {
    ID: 'Enlightened One',
    ReqLevel: '30',
    ReqSkill: '',
    ReqRank: '',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: 'BylethM, BylethF',
    UnitType: 'Magic',
    SwordProficiency: '3',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '2',
    ReasonProficiency: '-',
    FaithProficiency: '3',
    AuthorityProficiency: '3',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '20',
    GrowthStr: '10',
    GrowthMag: '10',
    GrowthDex: '-',
    GrowthSpd: '-',
    GrowthLck: '-',
    GrowthDef: '5',
    GrowthRes: '-',
    GrowthCha: '5',
    Movement: '6',
    '': '',
  },
  {
    ID: 'Emperor',
    ReqLevel: '30',
    ReqSkill: '',
    ReqRank: '',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: 'Edelgard',
    UnitType: 'Armor',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: '3',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '3',
    ArmorProficiency: '3',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '30',
    GrowthStr: '10',
    GrowthMag: '10',
    GrowthDex: '-',
    GrowthSpd: '-',
    GrowthLck: '-',
    GrowthDef: '5',
    GrowthRes: '5',
    GrowthCha: '10',
    Movement: '5',
    '': '',
  },
  {
    ID: 'Great Lord',
    ReqLevel: '30',
    ReqSkill: '',
    ReqRank: '',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: 'Dimitri',
    UnitType: '',
    SwordProficiency: '3',
    LanceProficiency: '3',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '3',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '30',
    GrowthStr: '10',
    GrowthMag: '-',
    GrowthDex: '10',
    GrowthSpd: '-',
    GrowthLck: '-',
    GrowthDef: '5',
    GrowthRes: '-',
    GrowthCha: '10',
    Movement: '6',
    '': '',
  },
  {
    ID: 'Barbarossa',
    ReqLevel: '30',
    ReqSkill: '',
    ReqRank: '',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: 'Claude',
    UnitType: 'Flying',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '3',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '3',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '3',
    GrowthHP: '30',
    GrowthStr: '15',
    GrowthMag: '-',
    GrowthDex: '-',
    GrowthSpd: '10',
    GrowthLck: '-',
    GrowthDef: '5',
    GrowthRes: '-',
    GrowthCha: '10',
    Movement: '8',
    '': '',
  },
  {
    ID: 'Falcon Knight',
    ReqLevel: '30',
    ReqSkill: 'Sword, Lance, Flying',
    ReqRank: 'C, A, B+',
    OneReq: '-',
    ReqGender: 'F',
    CharacterExclusive: '',
    UnitType: 'Flying',
    SwordProficiency: '3',
    LanceProficiency: '3',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '3',
    GrowthHP: '30',
    GrowthStr: '10',
    GrowthMag: '-',
    GrowthDex: '-',
    GrowthSpd: '20',
    GrowthLck: '-',
    GrowthDef: '-',
    GrowthRes: '5',
    GrowthCha: '10',
    Movement: '9',
    '': '',
  },
  {
    ID: 'Wyvern Lord',
    ReqLevel: '30',
    ReqSkill: 'Lance, Axe, Flying',
    ReqRank: 'C, A, A',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Flying',
    SwordProficiency: '-',
    LanceProficiency: '3',
    AxeProficiency: '3',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '3',
    GrowthHP: '30',
    GrowthStr: '15',
    GrowthMag: '-5',
    GrowthDex: '-',
    GrowthSpd: '10',
    GrowthLck: '-',
    GrowthDef: '5',
    GrowthRes: '-',
    GrowthCha: '5',
    Movement: '8',
    '': '60',
  },
  {
    ID: 'Mortal Savant',
    ReqLevel: '30',
    ReqSkill: 'Sword, Reason',
    ReqRank: 'A, B+',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Magic',
    SwordProficiency: '3',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '3',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '20',
    GrowthStr: '10',
    GrowthMag: '10',
    GrowthDex: '-',
    GrowthSpd: '-10',
    GrowthLck: '10',
    GrowthDef: '-',
    GrowthRes: '-',
    GrowthCha: '5',
    Movement: '6',
    '': '45',
  },
  {
    ID: 'Great Knight',
    ReqLevel: '30',
    ReqSkill: 'Axe, Armor, Riding',
    ReqRank: 'B+, A, B+',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Riding, Armor',
    SwordProficiency: '-',
    LanceProficiency: '3',
    AxeProficiency: '3',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '3',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '30',
    GrowthStr: '10',
    GrowthMag: '-',
    GrowthDex: '-',
    GrowthSpd: '-10',
    GrowthLck: '-',
    GrowthDef: '5',
    GrowthRes: '-5',
    GrowthCha: '5',
    Movement: '7',
    '': '',
  },
  {
    ID: 'Bow Knight',
    ReqLevel: '30',
    ReqSkill: 'Lance, Bow, Riding',
    ReqRank: 'C, A, A',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Riding',
    SwordProficiency: '-',
    LanceProficiency: '3',
    AxeProficiency: '-',
    BowProficiency: '3',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '3',
    FlyingProficiency: '-',
    GrowthHP: '10',
    GrowthStr: '-',
    GrowthMag: '-',
    GrowthDex: '-',
    GrowthSpd: '-5',
    GrowthLck: '-',
    GrowthDef: '-',
    GrowthRes: '-',
    GrowthCha: '5',
    Movement: '8',
    '': '',
  },
  {
    ID: 'Dark Knight',
    ReqLevel: '30',
    ReqSkill: 'Lance, Reason, Riding',
    ReqRank: 'C, B+, A',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Riding, Magic',
    SwordProficiency: '-',
    LanceProficiency: '3',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '3',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '3',
    FlyingProficiency: '-',
    GrowthHP: '10',
    GrowthStr: '5',
    GrowthMag: '10',
    GrowthDex: '-',
    GrowthSpd: '-5',
    GrowthLck: '-',
    GrowthDef: '5',
    GrowthRes: '10',
    GrowthCha: '5',
    Movement: '7',
    '': '',
  },
  {
    ID: 'Holy Knight',
    ReqLevel: '30',
    ReqSkill: 'Lance, Faith, Riding',
    ReqRank: 'C, B+, A',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Riding, Magic',
    SwordProficiency: '-',
    LanceProficiency: '3',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '-',
    FaithProficiency: '3',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '3',
    FlyingProficiency: '-',
    GrowthHP: '10',
    GrowthStr: '-',
    GrowthMag: '10',
    GrowthDex: '-',
    GrowthSpd: '-5',
    GrowthLck: '10',
    GrowthDef: '5',
    GrowthRes: '10',
    GrowthCha: '10',
    Movement: '7',
    '': '',
  },
  {
    ID: 'War Master',
    ReqLevel: '30',
    ReqSkill: 'Axe, Brawling',
    ReqRank: 'A, A',
    OneReq: '-',
    ReqGender: 'M',
    CharacterExclusive: '',
    UnitType: '',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: '3',
    BowProficiency: '-',
    BrawlingProficiency: '3',
    ReasonProficiency: '-',
    FaithProficiency: '-',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '40',
    GrowthStr: '15',
    GrowthMag: '-',
    GrowthDex: '-',
    GrowthSpd: '10',
    GrowthLck: '-',
    GrowthDef: '-',
    GrowthRes: '-',
    GrowthCha: '5',
    Movement: '6',
    '': '',
  },
  {
    ID: 'Gremory',
    ReqLevel: '30',
    ReqSkill: 'Reason, Faith',
    ReqRank: 'A, A',
    OneReq: '-',
    ReqGender: 'F',
    CharacterExclusive: '',
    UnitType: 'Magic',
    SwordProficiency: '-',
    LanceProficiency: '-',
    AxeProficiency: '-',
    BowProficiency: '-',
    BrawlingProficiency: '-',
    ReasonProficiency: '3',
    FaithProficiency: '3',
    AuthorityProficiency: '-',
    ArmorProficiency: '-',
    RidingProficiency: '-',
    FlyingProficiency: '-',
    GrowthHP: '10',
    GrowthStr: '-',
    GrowthMag: '10',
    GrowthDex: '10',
    GrowthSpd: '-',
    GrowthLck: '-',
    GrowthDef: '-',
    GrowthRes: '5',
    GrowthCha: '10',
    Movement: '6',
    '': '',
  },
  {
    ID: 'Trickster',
    ReqLevel: '0',
    ReqSkill: 'Sword, Faith',
    ReqRank: 'B, B',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Magic',
    SwordProficiency: '',
    LanceProficiency: '',
    AxeProficiency: '',
    BowProficiency: '',
    BrawlingProficiency: '',
    ReasonProficiency: '',
    FaithProficiency: '',
    AuthorityProficiency: '',
    ArmorProficiency: '',
    RidingProficiency: '',
    FlyingProficiency: '',
    GrowthHP: '',
    GrowthStr: '',
    GrowthMag: '',
    GrowthDex: '',
    GrowthSpd: '',
    GrowthLck: '',
    GrowthDef: '',
    GrowthRes: '',
    GrowthCha: '',
    Movement: '',
    '': '',
  },
  {
    ID: 'War Monk',
    ReqLevel: '0',
    ReqSkill: 'Brawling, Faith',
    ReqRank: 'B+, C+',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Magic',
    SwordProficiency: '',
    LanceProficiency: '',
    AxeProficiency: '',
    BowProficiency: '',
    BrawlingProficiency: '',
    ReasonProficiency: '',
    FaithProficiency: '',
    AuthorityProficiency: '',
    ArmorProficiency: '',
    RidingProficiency: '',
    FlyingProficiency: '',
    GrowthHP: '',
    GrowthStr: '',
    GrowthMag: '',
    GrowthDex: '',
    GrowthSpd: '',
    GrowthLck: '',
    GrowthDef: '',
    GrowthRes: '',
    GrowthCha: '',
    Movement: '',
    '': '',
  },
  {
    ID: 'Dark Flier',
    ReqLevel: '0',
    ReqSkill: 'Reason, Flying',
    ReqRank: 'B+, C+',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Flying, Magic',
    SwordProficiency: '',
    LanceProficiency: '',
    AxeProficiency: '',
    BowProficiency: '',
    BrawlingProficiency: '',
    ReasonProficiency: '',
    FaithProficiency: '',
    AuthorityProficiency: '',
    ArmorProficiency: '',
    RidingProficiency: '',
    FlyingProficiency: '',
    GrowthHP: '',
    GrowthStr: '',
    GrowthMag: '',
    GrowthDex: '',
    GrowthSpd: '',
    GrowthLck: '',
    GrowthDef: '',
    GrowthRes: '',
    GrowthCha: '',
    Movement: '',
    '': '',
  },
  {
    ID: 'Valkyrie',
    ReqLevel: '0',
    ReqSkill: 'Reason, Riding',
    ReqRank: 'B, B',
    OneReq: '-',
    ReqGender: 'M, F',
    CharacterExclusive: '',
    UnitType: 'Riding, Magic',
    SwordProficiency: '',
    LanceProficiency: '',
    AxeProficiency: '',
    BowProficiency: '',
    BrawlingProficiency: '',
    ReasonProficiency: '',
    FaithProficiency: '',
    AuthorityProficiency: '',
    ArmorProficiency: '',
    RidingProficiency: '',
    FlyingProficiency: '',
    GrowthHP: '',
    GrowthStr: '',
    GrowthMag: '',
    GrowthDex: '',
    GrowthSpd: '',
    GrowthLck: '',
    GrowthDef: '',
    GrowthRes: '',
    GrowthCha: '',
    Movement: '',
    '': '',
  },
];

export type ClassRaw = typeof data[number];
