# .github/workflows/ci.yaml

name: Pull request or push to Dev Branch

on:
  push:
    branches:
      - dev
      
jobs:
  build-and-deploy:
    timeout-minutes: 30
    name: Deploy website and sentry
    runs-on: ubuntu-latest
    
steps:
      - name: Checkout
        uses: actions/checkout@v1
        
- uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
- uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
- name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
        
- name: Build
        run: yarn build
        
- name: Generate 404 files
        run: |
          echo "---" > "./dist/apps/portfolio/404.html"
          echo "permalink: /404.html" >> "./dist/apps/<app-name>/404.html"
          echo "---" >> "./dist/apps/<app-name>/404.html"
          cat "./dist/apps/<app-name>/index.html" >> "./dist/apps/<app-name>/404.html"
          
- name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: master
          FOLDER: dist/apps/<app-name>
