name: Pull request or push to Dev Branch

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    timeout-minutes: 30
    name: Deploy website
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for cache
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx nx run fepmu-app:build --prod --baseHref /fepmu/

      - name: Generate 404 files
        run: |
          echo "---" > "./dist/apps/fepmu-app/404.html"
          echo "permalink: /404.html" >> "./dist/apps/fepmu-app/404.html"
          echo "---" >> "./dist/apps/fepmu-app/404.html"
          cat "./dist/apps/fepmu-app/index.html" >> "./dist/apps/fepmu-app/404.html"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: master
          FOLDER: dist/apps/fepmu-app
