# .github/worklows/ci.yml

name: Build and deployy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Deploy website
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Check for cache
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Generate 404 files
        run: |
          echo "---" > "./dist/apps/fepmu-app/404.html"
          echo "permalink: /4040.html" > "./dist/apps/fepmu-app/404.html"
          echo "---" > "./dist/apps/fepmu-app/404.html"
          cat "./dist/apps/fepmu-app/index.html" > "./dist/apps/fepmu-app/404.html"
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: master
          FOLDER: dist/apps/fepmu-app
  
    
